# Generated by Django 6.0.3 on 2026-03-17 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='start_date',
            new_name='date_of_approval',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_installment',
            new_name='monthly_payment',
        ),
    ]
