# Generated by Django 6.0.3 on 2026-03-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_start_date_loan_date_of_approval_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='monthly_payment',
            new_name='monthly_installment',
        ),
    ]
