# Generated by Django 6.0.3 on 2026-03-18 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_monthly_payment_loan_monthly_installment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='date_of_approval',
            new_name='start_date',
        ),
    ]
